# Generated by Django 4.2.16 on 2026-09-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_participation_role_attendeerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='badges/icons/'),
        ),
        migrations.AddField(
            model_name='badge',
            name='image',
            field=models.ImageField(blank=True, upload_to='badges/images/'),
        ),
    ]
