# Generated by Django 5.2.17 on 2026-09-24 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_message_file_message_file_name_message_invite_date_and_more'),
        ('portal', '0017_badge_icon_image_badge_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('text', models.CharField(max_length=500)),
                ('activity', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('chess', 'Chess'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('running', 'Running'), ('coffee', 'Coffee'), ('gaming', 'Gaming'), ('social', 'Connect')], default='social', max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_connections', to='jobs.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_connections', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='portal.networkpost')),
            ],
        ),
        migrations.AddIndex(
            model_name='networkpost',
            index=models.Index(fields=['pincode', 'is_open', '-created_at'], name='network_local_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='networkconnection',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_network_post_connection'),
        ),
    ]
