# Generated by Django 5.2.17 on 2026-09-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_networkpost_networkconnection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkpost',
            name='activity',
            field=models.CharField(choices=[('sports', 'Sports'), ('food', 'Food'), ('health', 'Health'), ('transport', 'Transport'), ('rent', 'Rent'), ('training', 'Training'), ('music', 'Music'), ('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('chess', 'Chess'), ('walking', 'Walking'), ('cycling', 'Cycling'), ('running', 'Running'), ('coffee', 'Coffee'), ('gaming', 'Gaming'), ('social', 'Connect')], default='social', max_length=20),
        ),
    ]
