# Generated by Django 5.2.17 on 2026-09-25 07:31

import django.core.validators
import django.db.models.deletion
import newsdesk.uploads
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_discount_district_industry_paymentplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=160)),
                ('theme', models.CharField(choices=[('sunshine', 'Sunshine'), ('rose', 'Rose'), ('sky', 'Sky')], default='sunshine', max_length=12)),
                ('is_public', models.BooleanField(default=False, help_text='Anyone with the link can see and download this card.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.pincode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(max_length=20000)),
                ('category', models.CharField(choices=[('news', 'News'), ('festivals', 'Festivals'), ('achievements', 'Achievements'), ('sports', 'Sports'), ('community', 'Community'), ('birthday', 'Birthday Wishes')], default='news', max_length=20)),
                ('kind', models.CharField(choices=[('news', 'News'), ('event', 'Event')], default='news', max_length=10)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('photo', models.ImageField(blank=True, storage=newsdesk.uploads.private_storage, upload_to=newsdesk.uploads.upload_path, validators=[newsdesk.uploads.validate_photo])),
                ('video', models.FileField(blank=True, storage=newsdesk.uploads.private_storage, upload_to=newsdesk.uploads.upload_path, validators=[newsdesk.uploads.validate_video])),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_items', to=settings.AUTH_USER_MODEL)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_items', to='jobs.pincode')),
            ],
            options={
                'ordering': ['-published_at', '-pk'],
                'permissions': [('manage_newsdesk', 'Manage all News Desk content and assignments')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160, validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newsdesk.newsitem')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='newsdesk.newsitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='newsdesk.comment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('comment', 'reporter'), name='news_one_report_per_user')],
            },
        ),
        migrations.AddIndex(
            model_name='newsitem',
            index=models.Index(fields=['pincode', 'status', '-published_at'], name='newsdesk_ne_pincode_42c6d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='news_published_has_date'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='news_one_rating_per_user'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('stars__gte', 1), ('stars__lte', 5)), name='news_rating_one_to_five'),
        ),
    ]
