# Generated by Django 4.2.16 on 2026-09-17 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_salesman_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='localoffer',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
