# Generated by Django 5.2.17 on 2026-09-27 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0051_localoffer_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('company', 'Company'), ('shop', 'Shop'), ('recruiter', 'Recruiter / Placement Agency'), ('factory', 'Factory'), ('startup', 'Startup'), ('institution', 'Institution'), ('ngo', 'NGO'), ('hospital', 'Hospital'), ('hotel', 'Hotel / Restaurant'), ('farm', 'Farm'), ('individual_employer', 'Individual Employer'), ('employee', 'Employee'), ('individual', 'Individual'), ('freelancer', 'Freelancer'), ('advertiser', 'Advertiser'), ('marketing_agent', 'Smart Marketing Agent'), ('family_child', 'Family Child Account')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='MarketingAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_shops', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agent', 'shop'), name='unique_marketing_access')],
            },
        ),
    ]
