# Generated by Django 5.2.17 on 2026-09-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_alter_user_user_type_marketingaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='all_states',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('scoped_admin', 'Assigned Admin'), ('super_admin', 'Super Admin'), ('state_admin', 'State Admin'), ('district_admin', 'District Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('', 'Regular User'), ('scoped_admin', 'Assigned Admin'), ('super_admin', 'Super Admin'), ('state_admin', 'State Admin'), ('district_admin', 'District Admin')], default='', max_length=20),
        ),
    ]
