# Generated by Django 4.2.16 on 2026-09-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_salesman_biz_id'),
        ('coupons', '0002_couponbatch_distributed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='redemption_shop',
            field=models.ForeignKey(blank=True, help_text='Only this shop account may verify and fulfil this reward.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opc_rewards', to='jobs.shopprofile'),
        ),
    ]
