# Generated by Django 4.2.16 on 2026-09-17 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0003_reward_redemption_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('salesman', 'business'), name='unique_salesman_business_shop'),
        ),
    ]
