# Generated by Django 5.2.17 on 2026-09-24 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_shop_business_shop_unique_salesman_business_shop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponbatch',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Silver'), ('G', 'Gold'), ('P', 'Points'), ('C', 'Complimentary')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='spinwheelslot',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Silver'), ('G', 'Gold'), ('P', 'Points'), ('C', 'Complimentary')], default='', help_text='Blank slots are the default for categories without their own slots.', max_length=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('activated', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='LuckyDrawEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='draw_entry', to='coupons.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lucky_draw_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the draw month.', unique=True)),
                ('prize', models.CharField(blank=True, max_length=200)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_draw', to='coupons.luckydrawentry')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='draw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='coupons.monthlydraw'),
        ),
        migrations.AddConstraint(
            model_name='monthlydraw',
            constraint=models.CheckConstraint(condition=models.Q(('month__day', 1)), name='draw_month_first_day'),
        ),
    ]
