# Generated by Django 4.2.16 on 2026-09-16 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{5}$', 'Enter a valid six-digit pincode.')]),
        ),
    ]
