# Generated by Django 4.2.16 on 2026-09-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_add_gender_to_familymember'),
    ]

    operations = [
        migrations.AddField(
            model_name='familysetup',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
