# Generated by Django 5.2.17 on 2026-10-03 17:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tuition.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('community', '0036_familysetup_is_public'), ('jobs', '0054_adminactivity'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120)])),
                ('age_as_of', models.DateField(default=django.utils.timezone.localdate)),
                ('guardian_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Enter a six-digit PIN code.')])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_learners', to=settings.AUTH_USER_MODEL)),
                ('family_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.familymember')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tuition_learner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(max_length=80)),
                ('attestation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('revoked', 'Revoked'), ('disputed', 'Disputed')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verification', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='tuition.learner')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='in_app', max_length=20)),
                ('state', models.CharField(default='pending', max_length=10)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('inbox', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.usernotification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.notificationevent')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.subject')),
            ],
        ),
        migrations.AddField(
            model_name='learner',
            name='interests',
            field=models.ManyToManyField(blank=True, to='tuition.subject'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('teacher', 'Teacher'), ('academy', 'Academy')], max_length=12)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(default=tuition.models.identifier, editable=False, unique=True)),
                ('description', models.TextField()),
                ('qualifications', models.TextField(blank=True)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('min_age', models.PositiveSmallIntegerField(default=0)),
                ('max_age', models.PositiveSmallIntegerField(default=100)),
                ('mode', models.CharField(choices=[('offline', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('pincode', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Enter a six-digit PIN code.')])),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_source', models.CharField(blank=True, max_length=100)),
                ('radius_km', models.PositiveSmallIntegerField(default=0)),
                ('public_fees', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='pending', max_length=12)),
                ('mapped_pin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.pincode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_profiles', to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(blank=True, to='tuition.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'Enter a six-digit PIN code.')])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='tuition.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=100, unique=True)),
                ('mime', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.learner')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='tuition.teacherprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='guardianlink',
            constraint=models.UniqueConstraint(fields=('learner', 'user'), name='tuition_guardian_unique'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'recipient', 'channel'), name='tuition_delivery_unique'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.CheckConstraint(condition=models.Q(('min_age__lte', models.F('max_age'))), name='tuition_teacher_ages'),
        ),
        migrations.AddConstraint(
            model_name='servicearea',
            constraint=models.UniqueConstraint(fields=('teacher', 'pincode'), name='tuition_service_pin'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('learner__isnull', True), ('teacher__isnull', False)), models.Q(('learner__isnull', False), ('teacher__isnull', True)), _connector='OR'), name='tuition_media_parent'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='tuition_available_times'),
        ),
    ]
