# Generated by Django 5.2.17 on 2026-10-03 18:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('tuition', '0003_schedule_finance'), ('jobs', '0054_adminactivity'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('certificate', 'Certificate'), ('level_completion', 'Level Completion'), ('attendance_award', 'Attendance Award'), ('performance', 'Performance'), ('competition', 'Competition'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('public_requested', models.BooleanField(default=False)),
                ('moderation', models.CharField(default='pending', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('moderation', models.CharField(default='pending', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('registered', 'Registered'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='invited', max_length=12)),
                ('safety_consent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award', models.CharField(choices=[('winner', 'Winner'), ('runner_up', 'Runner Up'), ('participation', 'Participation'), ('special', 'Special')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('placement', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('moderation', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('annual_day', 'Annual Day'), ('performance', 'Performance'), ('workshop', 'Workshop'), ('examination', 'Examination'), ('exhibition', 'Exhibition'), ('sports_day', 'Sports Day'), ('trip', 'Trip'), ('competition', 'Competition'), ('festival', 'Festival')], max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.CharField(max_length=250)),
                ('mode', models.CharField(choices=[('offline', 'In person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('public', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=12)),
                ('moderation', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='LevelDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('threshold', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='PointEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_version', models.PositiveIntegerField()),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=180)),
                ('source_revision', models.CharField(max_length=60)),
                ('action_key', models.CharField(max_length=180, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('attendance', 'Attendance'), ('assignment', 'Assignment'), ('performance', 'Performance'), ('competition', 'Competition'), ('achievement', 'Achievement')], max_length=20)),
                ('value', models.PositiveIntegerField(default=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('venue', models.CharField(max_length=250)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('moderation', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('completed', 'Completed'), ('returned', 'Returned')], default='submitted', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='enrolment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='tuition.enrolment'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='tuition.teacherprofile'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.batch'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.lesson'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='tuition.teacherprofile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.batch'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='tuition.lesson'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.enrolment'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.learner'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='tuition.eventparticipation'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.eventresult'),
        ),
        migrations.AddField(
            model_name='learningevent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='tuition.teacherprofile'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='tuition.learningevent'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.learningevent'),
        ),
        migrations.AddField(
            model_name='leveldefinition',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='tuition.teacherprofile'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.leveldefinition'),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.achievement'),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.attendance'),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_entries', to='tuition.enrolment'),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.eventresult'),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='reverses',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='tuition.pointentry'),
        ),
        migrations.AddField(
            model_name='pointrule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_rules', to='tuition.teacherprofile'),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.pointrule'),
        ),
        migrations.AddField(
            model_name='programmeitem',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programme', to='tuition.learningevent'),
        ),
        migrations.AddField(
            model_name='programmeitem',
            name='participants',
            field=models.ManyToManyField(blank=True, to='tuition.eventparticipation'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='tuition.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.enrolment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointentry',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.submission'),
        ),
        migrations.AddConstraint(
            model_name='eventresult',
            constraint=models.UniqueConstraint(fields=('participation', 'award'), name='tuition_participant_award'),
        ),
        migrations.AddConstraint(
            model_name='learningevent',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start')), ('registration_end__gte', models.F('registration_start')), ('registration_end__lte', models.F('end')), ('capacity__gt', 0)), name='tuition_event_dates'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipation',
            constraint=models.UniqueConstraint(fields=('event', 'learner'), name='tuition_event_learner'),
        ),
        migrations.AddConstraint(
            model_name='leveldefinition',
            constraint=models.UniqueConstraint(fields=('teacher', 'name'), name='tuition_level_name'),
        ),
        migrations.AddConstraint(
            model_name='leveldefinition',
            constraint=models.UniqueConstraint(fields=('teacher', 'threshold'), name='tuition_level_threshold'),
        ),
        migrations.AddConstraint(
            model_name='pointrule',
            constraint=models.UniqueConstraint(fields=('teacher', 'source'), name='tuition_point_rule'),
        ),
        migrations.AddConstraint(
            model_name='programmeitem',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='tuition_programme_dates'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'enrolment'), name='tuition_submission_unique'),
        ),
        migrations.AddConstraint(
            model_name='pointentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('achievement__isnull', True), ('attendance__isnull', False), ('result__isnull', True), ('submission__isnull', True)), models.Q(('achievement__isnull', True), ('attendance__isnull', True), ('result__isnull', True), ('submission__isnull', False)), models.Q(('achievement__isnull', True), ('attendance__isnull', True), ('result__isnull', False), ('submission__isnull', True)), models.Q(('achievement__isnull', False), ('attendance__isnull', True), ('result__isnull', True), ('submission__isnull', True)), _connector='OR'), name='tuition_point_source'),
        ),
    ]
