# Generated by Django 5.2.17 on 2026-10-03 18:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('tuition', '0004_achievement_announcement_assignment_and_more')]
    operations = [
        migrations.CreateModel(
            name='MediaSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_revision', models.PositiveIntegerField()),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('allow_media', models.BooleanField(default=False)),
                ('policy_version', models.CharField(default='1', max_length=20)),
                ('adult_self', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='tuition_media_parent',
        ),
        migrations.AddField(
            model_name='learner',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='moderation',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='public_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='subjects_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='tuition.achievement'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='tuition.learningevent'),
        ),
        migrations.AddField(
            model_name='mediasubject',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='tuition.mediaasset'),
        ),
        migrations.AddField(
            model_name='mediasubject',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.learner'),
        ),
        migrations.AddField(
            model_name='publicationconsent',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.achievement'),
        ),
        migrations.AddField(
            model_name='publicationconsent',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.mediaasset'),
        ),
        migrations.AddField(
            model_name='publicationconsent',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationconsent',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.learner'),
        ),
        migrations.AddField(
            model_name='publicationconsent',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.programmeitem'),
        ),
        migrations.AddField(
            model_name='publicationconsent',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.eventresult'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media', to='tuition.submission'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('achievement__isnull', True), ('event__isnull', True), ('learner__isnull', True), ('submission__isnull', True), ('teacher__isnull', False)), models.Q(('achievement__isnull', True), ('event__isnull', True), ('learner__isnull', False), ('submission__isnull', True), ('teacher__isnull', True)), models.Q(('achievement__isnull', False), ('event__isnull', True), ('learner__isnull', True), ('submission__isnull', True), ('teacher__isnull', True)), models.Q(('achievement__isnull', True), ('event__isnull', False), ('learner__isnull', True), ('submission__isnull', True), ('teacher__isnull', True)), models.Q(('achievement__isnull', True), ('event__isnull', True), ('learner__isnull', True), ('submission__isnull', False), ('teacher__isnull', True)), _connector='OR'), name='tuition_media_parent_v2'),
        ),
        migrations.AddConstraint(
            model_name='mediasubject',
            constraint=models.UniqueConstraint(fields=('asset', 'learner'), name='tuition_media_subject'),
        ),
        migrations.AddConstraint(
            model_name='publicationconsent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('achievement__isnull', False), ('asset__isnull', True), ('programme__isnull', True), ('result__isnull', True)), models.Q(('achievement__isnull', True), ('asset__isnull', False), ('programme__isnull', True), ('result__isnull', True)), models.Q(('achievement__isnull', True), ('asset__isnull', True), ('programme__isnull', False), ('result__isnull', True)), models.Q(('achievement__isnull', True), ('asset__isnull', True), ('programme__isnull', True), ('result__isnull', False)), _connector='OR'), name='tuition_consent_target'),
        ),
    ]
