# Generated by Django 5.2.17 on 2026-10-03 18:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('tuition', '0005_media_consent')]
    operations = [
        migrations.CreateModel(
            name='TuitionComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuitionConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tuitioncomplaint',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.mediaasset'),
        ),
        migrations.AddField(
            model_name='tuitioncomplaint',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_context', to='jobs.complaint'),
        ),
        migrations.AddField(
            model_name='tuitioncomplaint',
            name='enrolment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.enrolment'),
        ),
        migrations.AddField(
            model_name='tuitioncomplaint',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tuition.learningevent'),
        ),
        migrations.AddField(
            model_name='tuitioncomplaint',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.teacherprofile'),
        ),
        migrations.AddField(
            model_name='tuitionconversation',
            name='adult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tuitionconversation',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tuition_context', to='jobs.conversation'),
        ),
        migrations.AddField(
            model_name='tuitionconversation',
            name='enrolment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tuition.enrolment'),
        ),
        migrations.AddConstraint(
            model_name='tuitionconversation',
            constraint=models.UniqueConstraint(fields=('enrolment', 'adult'), name='tuition_thread_unique'),
        ),
    ]
