# Generated by Django 5.2.17 on 2026-10-09 07:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_integrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tuition.mediaasset'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tuition.mediaasset'),
        ),
        migrations.CreateModel(
            name='AcademyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$')])),
                ('public', models.BooleanField(default=False, help_text="I have this teacher's permission to publish their name, subjects and approved photo. Phone stays private.")),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='tuition.teacherprofile')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tuition.mediaasset')),
                ('subjects', models.ManyToManyField(blank=True, to='tuition.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
