# Generated by Django 5.2.17 on 2026-10-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0007_teacherprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='parent_academy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='tuition.teacherprofile'),
        ),
    ]
