# Generated by Django 5.2.17 on 2026-10-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0008_teacherprofile_parent_academy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingFileDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
