# Generated by Django 5.2.17 on 2026-10-09 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_pendingfiledeletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$')]),
        ),
    ]
