# Generated by Django 5.2.17 on 2026-10-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0010_application_parent_name_application_parent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('academic', 'Academic tuition'), ('sports', 'Sports'), ('fitness', 'Gym & Fitness'), ('cooking', 'Food & Cooking'), ('skills', 'Skills & Vocational Training'), ('music', 'Music'), ('dance', 'Dance'), ('arts', 'Arts & Crafts'), ('languages', 'Languages'), ('technology', 'Computers & Technology'), ('other', 'Other')], max_length=20),
        ),
    ]
