# Generated by Django 5.2.17 on 2026-10-10 05:52

from django.db import migrations, models


def copy_categories(apps, schema_editor):
    profiles = apps.get_model('tuition', 'TeacherProfile').objects.using(schema_editor.connection.alias)
    for category in profiles.exclude(category='').values_list('category', flat=True).distinct():
        profiles.filter(category=category).update(categories=[category])


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0011_teacherprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(copy_categories, migrations.RunPython.noop),
    ]
