# Generated by Django 5.2.17 on 2026-10-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0012_teacherprofile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='category_subjects',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
