"""
Django settings for jobportal project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from importlib import import_module
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file if present (development convenience)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

def env_bool(name, default):
    value = os.environ.get(name, str(default)).strip().lower()
    if value in {'true', '1', 'yes', 'on'}:
        return True
    if value in {'false', '0', 'no', 'off'}:
        return False
    raise ImproperlyConfigured(f'{name} must be a boolean.')


def env_list(name, default):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def env_int(name, default, minimum=0):
    try:
        value = int(os.environ.get(name, str(default)))
    except ValueError as exc:
        raise ImproperlyConfigured(f'{name} must be an integer.') from exc
    if value < minimum:
        raise ImproperlyConfigured(f'{name} must be at least {minimum}.')
    return value


def env_path(name, default):
    value = os.environ.get(name, str(default)).strip()
    if not value:
        raise ImproperlyConfigured(f'{name} must be a non-empty filesystem path.')
    try:
        path = Path(value).expanduser()
        return (path if path.is_absolute() else BASE_DIR / path).resolve()
    except (OSError, RuntimeError, ValueError) as exc:
        raise ImproperlyConfigured(f'{name} must be a valid filesystem path.') from exc


def paths_overlap(first, second):
    return first == second or first in second.parents or second in first.parents


SITE_NAME = 'OUR PINCODE'
SITE_TAGLINE = 'Find Jobs Near You. Hire People Near You.'
SITE_URL = os.environ.get('SITE_URL', 'https://ourpincode.com').strip().rstrip('/')
try:
    _site_url = urlsplit(SITE_URL)
    _site_port = _site_url.port  # Access validates numeric ports and their range.
except ValueError as exc:
    raise ImproperlyConfigured('SITE_URL must contain a valid hostname and port.') from exc
if (_site_url.scheme not in {'http', 'https'} or not _site_url.hostname
        or _site_url.username or _site_url.password
        or _site_url.path or _site_url.query or _site_url.fragment
        or _site_url.netloc.endswith(':') or _site_port == 0):
    raise ImproperlyConfigured('SITE_URL must be an HTTP(S) origin without credentials or a path.')

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY.strip():
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is required.')

DEBUG = env_bool('DJANGO_DEBUG', False)
ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'ourpincode.com,www.ourpincode.com')
CSRF_TRUSTED_ORIGINS = env_list(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'https://ourpincode.com,https://www.ourpincode.com',
)

ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GOOGLE_MAPS_KEY = os.environ.get('GOOGLE_MAPS_KEY', '')
TWO_FACTOR_API_KEY = os.environ.get('TWO_FACTOR_API_KEY', '')
TWO_FACTOR_OTP_TEMPLATE = os.environ.get('TWO_FACTOR_OTP_TEMPLATE', 'OTP1')

# Only a trusted reverse proxy may reach the application. It must overwrite
# X-Forwarded-Proto rather than trusting a client-supplied value.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
# Enable HSTS only after the HTTPS deployment has been verified.
SECURE_HSTS_SECONDS = env_int('DJANGO_SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', True)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', True)
CSRF_COOKIE_HTTPONLY = False  # JavaScript reads the token for AJAX.
X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jobs',
    'health',
    'vouchers',
    'community',
    'campus',
    'portal',
    'coupons',
    'quiz',
    'newsdesk',
]

AUTH_USER_MODEL = 'jobs.User'

AUTHENTICATION_BACKENDS = [
    'jobs.backends.PhoneOrEmailBackend',
    'jobs.backends.FamilyAccountBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL          = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'jobportal.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'jobportal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'jobs.context_processors.site_ads',
                'jobportal.context_processors.site_branding',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobportal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     os.environ.get('DB_NAME', 'ourpincode_db'),
        'USER':     os.environ.get('DB_USER', 'ourpincode_app'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST':     os.environ.get('DB_HOST', 'localhost'),
        'PORT':     os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_ALL_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
_storage_base = BASE_DIR.parent / f'{BASE_DIR.name}-data'
STATIC_ROOT = env_path('STATIC_ROOT', _storage_base / 'staticfiles')
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL  = '/media/'
MEDIA_ROOT = env_path('MEDIA_ROOT', _storage_base / 'media')
for _name, _path in (('STATIC_ROOT', STATIC_ROOT), ('MEDIA_ROOT', MEDIA_ROOT)):
    if paths_overlap(_path, BASE_DIR):
        raise ImproperlyConfigured(f'{_name} must not overlap the project checkout.')
if paths_overlap(STATIC_ROOT, MEDIA_ROOT):
    raise ImproperlyConfigured('STATIC_ROOT and MEDIA_ROOT must not overlap.')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Email (configure a verified delivery provider) ───────────────────────────────────────────────────────
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = env_int('EMAIL_PORT', 587, minimum=1)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.')
EMAIL_TIMEOUT = env_int('EMAIL_TIMEOUT', 10, minimum=1)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'OUR PINCODE <noreply@ourpincode.com>')

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# ── Cache (file-based, shared across workers) ────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': str(env_path('CACHE_LOCATION', BASE_DIR / '.cache')),
        'TIMEOUT': 300,
    }
}

# ── Logging ───────────────────────────────────────────────────────────────────
# Production: Daphne writes stderr to the systemd journal (service: ourpincode).
# Read logs with: sudo journalctl -u ourpincode -f
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Application loggers — ERROR+ always; includes full traceback via logger.exception()
        'jobs': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'community': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'portal': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'health': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'campus': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'vouchers': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django framework — request errors and security warnings
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# Legacy overrides are development-only, explicitly enabled by DJANGO_DEBUG.
# Production always retains the environment-derived, validated configuration.
if DEBUG:
    try:
        _local_settings = import_module('jobportal.local_settings')
    except ModuleNotFoundError as exc:
        if exc.name != 'jobportal.local_settings':
            raise
    else:
        globals().update({name: value for name, value in vars(_local_settings).items()
                          if name.isupper()})

# ── Sentry error monitoring ───────────────────────────────────────────────────
# Activated only when SENTRY_DSN env var is set (production/staging).
# Never set SENTRY_DSN in development — errors stay local.
_SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if _SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration
    import logging

    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            # Capture WARNING+ log messages as breadcrumbs; ERROR+ as events
            LoggingIntegration(level=logging.WARNING, event_level=logging.ERROR),
        ],
        # Capture 10 % of transactions for performance data (low overhead)
        traces_sample_rate=0.1,
        # Do not send passwords, tokens, OTPs, or card numbers
        send_default_pii=False,
        environment=os.environ.get('DJANGO_ENV', 'production'),
        release=os.environ.get('GIT_COMMIT', ''),
    )

# Channels
ASGI_APPLICATION = 'jobportal.asgi.application'
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}
